FROM eclipse-temurin:17-jdk

COPY target/*.jar tipocambio.jar

#SE ESPECIFICA EL PUERTO PARA SABER QUE PUERTO SE CONFIGURO EN LA APLICACION
#NO SOBREESCRIBE EL PUERTO QUE SE CONFIGURO EN LA APLICACION
EXPOSE 8081

ENTRYPOINT ["java", "-jar", "tipocambio.jar"]

